[package]
name = "mari"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
criterion = { version = "0.3.5", features = ["html_reports"] }

[[bench]]
name = "example"
harness = false

[package.metadata.nix]
build = true
